import numpy as np
import re
from datetime import datetime as dt
import pandas as pd
import json

from nomad.datamodel.metainfo.basesections import (
    ElementalComposition,
    Activity,
    PureSubstance,
    CompositeSystem,
    Measurement,
    Process,
    Collection,
    EntityReference,
    CompositeSystemReference,
    SectionReference,
    Experiment
)
from nomad.datamodel.metainfo.annotations import (
    ELNAnnotation,
)
from nomad.parsing.tabular import TableData
from structlog.stdlib import (
    BoundLogger,
)
from nomad.metainfo import (
    MSection,
    Package,
    Quantity,
    SubSection,
    MEnum,
    Reference,
    Datetime,
    Section,
    QuantityReference
)
from nomad.datamodel.data import (
    EntryData,
    ArchiveSection,
    Author
)

from laytec_epitt import LayTec_EpiTT_Measurement

m_package = Package(name='movpe_IMEM')


class Notes(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    notes = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Overview/Notes"},
        a_eln={
            "component": "RichTextEditQuantity"})


class Users(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    user = Quantity(
        type=Author,
        description='FILL',
        a_tabular={
            "name": "Overview/Operator"},
        a_eln={
            "component": "AuthorEditQuantity"})


class ElementalComposition(ElementalComposition):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    element = Quantity(
        type=str,
        a_tabular={
            "name": "Substrate/Elements"
        },
        a_eln={
            "component": "StringEditQuantity"
        },
    )


class Parallelepiped(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    height = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "nanometer"
        },
        unit="nanometer",
    )
    width = Quantity(
        type=np.float64,
        description='substrate dimension X',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        a_tabular={
            "name": "Substrate/Size X"
        },
        unit="millimeter",
    )
    length = Quantity(
        type=np.float64,
        description='substrate dimension Y',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        a_tabular={
            "name": "Substrate/Size Y"
        },
        unit="millimeter",
    )
    surface_area = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 2"
        },
        unit="millimeter ** 2",
    )
    volume = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 3"
        },
        unit="millimeter ** 3",
    )


class Cylinder(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    height = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "nanometer"
        },
        unit="nanometer",
    )
    radius = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        unit="millimeter",
    )
    lower_cap_radius = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "inch"
        },
        unit="inch",
        a_tabular={
            "name": "Substrate/Size Diameter"}
    )
    upper_cap_radius = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        unit="millimeter",
    )
    cap_surface_area = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 2"
        },
        unit="millimeter ** 2",
    )
    lateral_surface_area = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 2"
        },
        unit="millimeter ** 2",
    )
    volume = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 3"
        },
        unit="millimeter ** 3",
    )


class Geometry(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)
    parallelepiped = SubSection(
        section_def=Parallelepiped,
    )
    cylinder = SubSection(
        section_def=Cylinder,
    )


class Precursor(PureSubstance, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    name = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Substance Name"
        },
    )
    cas_number = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
            "label": "CAS number"
        },
        a_tabular={
            "name": "Precursors/CAS"},
    )
    phase = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
        },
        a_tabular={
            "name": "Precursors/Phase"},
    )
    description = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
        },
        a_tabular={
            "name": "Precursors/Description"},
    )
    supplier = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
        },
        a_tabular={
            "name": "Precursors/Supplier"},
    )
    buying_date = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
        },
        a_tabular={
            "name": "Precursors/Buying date"},
    )
    opening_date = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
        },
        a_tabular={
            "name": "Precursors/Opening date"},
    )
    notes = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
        },
        a_tabular={
            "name": "Precursors/Notes"},
    )


class Precursors(EntityReference):
    '''
    A section used for referencing a Precursor.
    '''
    reference = Quantity(
        type=Precursor,
        description='A reference to a NOMAD `Precursor` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Precursor Reference',
        ),
    )


class Substrate(CompositeSystem, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''

    m_def = Section(
        label_quantity='lab_id'
    )

    alias = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Substrate ID"})
    name = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Material"})
    lab_id = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Substrates"})
    supplier = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Supplier"})
    orientation = Quantity(
        type=str,
        description='crystallographic orientation of the substrate in [hkl]',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Orientation"})
    off_cut = Quantity(
        type=np.float64,
        description='Off-cut angle to the substrates surface',
        a_eln={
            "component": "NumberEditQuantity"},
        a_tabular={
            "name": "Substrate/Off-cut"},
    )
    off_cut_orientation = Quantity(
        type=str,
        description='orientation of Off-cut angle to the substrates surface',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Off-cut Orientation"},
        )
    doping_level = Quantity(
        type=np.float64,
        description='Chemical doping level of electrically conductive substrates',
        a_eln={
            "component": "NumberEditQuantity"},
        a_tabular={
            "name": "Substrate/Doping Level"})
    doping_species = Quantity(
        type=str,
        description='Doping species to obtain electrical conductivity in the substrates',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Doping species"})
    susceptor = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Susceptor"})
    mask = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Mask"})
    pocket = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Pocket"})
    annealing = Quantity(
        type=bool,
        description='Is the sample annealed?',
        a_eln={
            "component": "BoolEditQuantity"},
        a_tabular={
            "name": "Substrate/Annealing"})
    cleaning = Quantity(
        type=bool,
        description='FILL',
        a_eln={
            "component": "BoolEditQuantity"},
        a_tabular={
            "name": "Substrate/Cleaning"})
    regrowth = Quantity(
        type=bool,
        description='FILL',
        a_eln={
            "component": "BoolEditQuantity"},
        a_tabular={
            "name": "Substrate/Regrowth"})
    notes = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"})
    geometry = SubSection(
        section_def=Geometry,
    )
    elemental_composition = SubSection(
        section_def=ElementalComposition,
        repeats=True,
    )


class Substrates(CompositeSystemReference):
    '''
    A section used for referencing a Substrate.
    '''
    reference = Quantity(
        type=Substrate,
        description='A reference to a NOMAD `Substrate` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Substrate Reference',
        ),
    )
    substrate_temperature = Quantity(
        type=np.float64,
        description='temperature of the substrate',
        a_tabular={
            "name": "Overview/Substrate T"},
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"},
        unit="celsius")

    # def normalize(self, archive, logger: BoundLogger) -> None:
    #     '''
    #     The normalizer for the `Substrates` class.
    #     '''
    #     super(Substrates, self).normalize(archive, logger)

        # if self.reference:
        #     setattr(self,'name', self.reference.lab_id)


class ParentSamples(CompositeSystemReference):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    reference = Quantity(
        type=CompositeSystem,
        description='A reference to a NOMAD `ParentSample` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Parent Sample Reference',
        ),
    )
    lab_id = Quantity(
        type=str,
        description='the sample used for this step of growth',
        a_tabular={
            "name": "GrowthRun/Previous Layer Name"
        },
        a_eln={
            "label": "Previous Layer ID"
        },
    )


class GrownSample(CompositeSystem, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        more={
            "label_quantity": "lab_id"
        },)

    lab_id = Quantity(
        type=str,
        description='the sample used for this step of growth',
        a_tabular={
            "name": "GrowthRun/Sample Name"
        },
        a_eln={
            "label": "Sample ID"
        },
    )
    test_quantities = Quantity(
        type=str,
        description='Test quantity',
        a_eln={
            "component": "StringEditQuantity"
        },
    )


class GrownSamples(CompositeSystemReference):
    '''
    A section used for referencing a Grown Sample.
    '''
    reference = Quantity(
        type=GrownSample,
        description='A reference to a NOMAD `GrownSample` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='GrownSample Reference',
        ),
    )


class Bubblers(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        more={
            "label_quantity": "material"
        },)
    material = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Material"
        },
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    mass_flow_controller = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler MFC"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    pressure = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Pressure"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )
    dilution = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Dilution"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    source = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Source"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    inject = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Inject"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Temp"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )
    partial_pressure = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Partial Pressure"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )
    molar_flux = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Molar Flux"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mol / minute"
        },
        unit="mol / minute",
    )


class GasSource(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        more={
            "label_quantity": "material"
        },)
    material = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Gas Material"
        },
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    mass_flow_controller = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Gas MFC"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    molar_flux = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Gas Molar Flux"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )


class MistSourceComponents(ArchiveSection):
    '''Class autogenerated from yaml schema.'''

    material = Quantity(
        type=str, description='FILL', a_eln={
            "component": "StringEditQuantity"}, a_tabular={
            "name": "Mist/Material"})
    concentration = Quantity(
        type=np.float64,
        description='FILL',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplyUnit": "mol / liter"},
        a_tabular={
            "name": "Mist/Concentration"},
        unit="mol / liter")


class MistSource(ArchiveSection):
    '''Class autogenerated from yaml schema.'''

    m_def = Section(more={"label_quantity": "material"})

    material_flow = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/MIST Flow MFC"},
        a_eln={
            "component": "StringEditQuantity"})
    valve = Quantity(
        type=bool,
        description='is valve open? True/False',
        a_tabular={
            "name": "GrowthRun/MIST Valve"},
        a_eln={
            "component": "BoolEditQuantity"})
    item = Quantity(
        type=str,
        description='FILL',
        a_tabular={
            "name": "Mist/Item"},
        a_eln={
            "component": "StringEditQuantity"})
    temperature = Quantity(
        type=np.float64, description='FILL',
        a_eln={
            "component": "NumberEditQuantity", "defaultDisplyUnit": "celsius"},
        a_tabular={
            "name": "Mist/Temperature"},
        unit="celsius")
    time = Quantity(
        type=np.float64,
        description='FILL',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplyUnit": "minute"},
        a_tabular={
            "name": "Mist/Time"},
        unit="minute")
    notes = Quantity(
        type=str,
        description='FILL',
        a_tabular={
            "name": "Mist/Notes"},
        a_eln={
            "component": "StringEditQuantity"})

    components = SubSection(section_def=MistSourceComponents, repeats=True)


class PregrowthStep(ArchiveSection):
    '''Class autogenerated from yaml schema.'''
    m_def = Section(a_eln=None)
    step_number = Quantity(
        type=int, description='sequential number of the step on going', a_eln={
            "component": "NumberEditQuantity"}, a_tabular={
            "name": "Pregrowth/Step Index"})
    name = Quantity(type=str, description='what this step consists of', a_tabular={
                    "name": "Pregrowth/Step Name"}, a_eln={"component": "StringEditQuantity"})
    description = Quantity(
        type=str,
        description='FILL',
        a_tabular={
            "name": "Pregrowth/Description"},
        a_eln={
            "component": "StringEditQuantity"})
    elapsed_time = Quantity(
        type=np.float64, description='FILL', a_eln={
            "component": "NumberEditQuantity"}, a_tabular={
            "name": "Pregrowth/Duration"}, unit="minute")
    carrier_gas_flow = Quantity(
        type=np.float64,
        description='FILL',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"},
        a_tabular={
            "name": "Pregrowth/Carrier Gas Flow"},
        unit="cm ** 3 / minute")
    carrier_gas = Quantity(
        type=str,
        description='FILL',
        a_tabular={
            "name": "Pregrowth/Carrier Gas"},
        a_eln={
            "component": "StringEditQuantity"})
    chamber_pressure = Quantity(
        type=np.float64,
        description='FILL', a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"},
        a_tabular={
            "name": "Pregrowth/Chamber Pressure"},
        unit="mbar")
    substrate_temperature = Quantity(
        type=np.float64, description='FILL', a_eln={
            "component": "NumberEditQuantity", "defaultDisplayUnit": "celsius"}, a_tabular={
            "name": "Pregrowth/Substrate Temperature"}, unit="celsius")
    carrier_rotation = Quantity(
        type=int, description='FILL', a_eln={
            "component": "NumberEditQuantity", "defaultDisplayUnit": "rpm"}, a_tabular={
            "name": "Pregrowth/Carrier Rotation"}, unit="rpm")
    notes = Quantity(
        type=str,
        description='FILL',
        a_tabular={
            "name": "Pregrowth/Notes"},
        a_eln={
            "component": "StringEditQuantity"})


class Pregrowth(Process, EntryData):  # (Process, TableData):
    '''Class autogenerated from yaml schema.'''
    m_def = Section(a_eln=None)

    pregrowth_steps = SubSection(section_def=PregrowthStep, repeats=True)


class Pregrowths(SectionReference):
    '''
    A section used for referencing a Pregrowth.
    '''
    reference = Quantity(
        type=Pregrowth,
        description='A reference to a NOMAD `Pregrowth` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Pregrowth Reference',
        ),
    )


class GrowthRunStep(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)
    name = Quantity(
        type=str,
        description='what this step consists of',
        a_tabular={
            "name": "GrowthRun/Name"},
        a_eln={
            "component": "StringEditQuantity"
            }
        )
    elapsed_time = Quantity(
        type=np.float64,
        description='Past time since process start',
        a_tabular={
            "name": "GrowthRun/Duration"},
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"},
        unit="minute"
        )
    step_number = Quantity(
        type=int,
        description='sequential number of the step on going',
        a_tabular={
            "name": "GrowthRun/Step"},
        a_eln={
            "component": "NumberEditQuantity"}
        )
    temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Temperature"},
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"},
        unit="celsius"
        )
    pressure = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Pressure"},
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"},
        unit="mbar"
        )
    description = Quantity(
        type=str, description='FILL THE DESCRIPTION', a_eln={
            "component": "StringEditQuantity"}
        )
    purge_flow = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Purge Flow"},
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"},
        unit="cm ** 3 / minute"
        )
    uniform_valve = Quantity(
        type=int,
        description='inner valve (0-200)',
        a_tabular={
            "name": "GrowthRun/Uniform Valve"},
        a_eln={
            "component": "SliderEditQuantity",
            "minValue": 0,
            "maxValue": 200}
        )
    purge_valve = Quantity(
        type=int,
        description='inner valve (0-200)',
        a_tabular={
            "name": "GrowthRun/Purge Valve"},
        a_eln={
            "component": "SliderEditQuantity",
            "minValue": 0,
            "maxValue": 200}
        )

    bubblers = SubSection(
        section_def=Bubblers,
        repeats=True,
    )
    gas_source = SubSection(
        section_def=GasSource,
        repeats=True,
    )
    mist_source = SubSection(
        section_def=MistSource,
        repeats=True,
    )


class GrowthRun(Process, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "hide": [
                "steps"
            ]
        },
        # more={
        #     "label_quantity": "sample_id"
        # }
    )

    method = Quantity(
        type=str,
        default="Growth (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    lab_id = Quantity(
        type=str,
        description='the ID from RTG',
        a_tabular={
            "name": "GrowthRun/Recipe Name"
        },
        a_eln={
            "component": "StringEditQuantity",
            "label": "Growth ID"
        },
    )
    grown_samples = SubSection(
        section_def=GrownSamples,
        # repeats=True
    )
    parent_sample = SubSection(
        section_def=ParentSamples,
        repeats=True
    )
    growth_run_steps = SubSection(
        section_def=GrowthRunStep,
        repeats=True,
    )


class GrowthRuns(SectionReference):
    '''
    A section used for referencing a GrowthRun.
    '''
    reference = Quantity(
        type=GrowthRun,
        description='A reference to a NOMAD `GrowthRun` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Growth Run Reference',
        ),
    )


class InSituMonitorings(SectionReference):
    '''
    A section used for referencing a InSituMonitoring.
    '''
    reference = Quantity(
        type=LayTec_EpiTT_Measurement,
        description='A reference to a NOMAD `InSituMonitoring` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='In situ Monitoring Reference',
        ),
    )


class HallMeasurement(Measurement, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        more={
            "label_quantity": "sample_id"
        },)
    method = Quantity(
        type=str,
        default= "Hall (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    sample_id = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    datetime = Quantity(
        type=Datetime,
        a_eln={
            "component": "DateTimeEditQuantity"
        },
    )
    resistivity = Quantity(
        type=np.float64,
        description='FILL',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "ohm / cm"
        },
        unit="ohm / cm",
    )
    mobility = Quantity(
        type=np.float64,
        description='FILL',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm**2 / volt / second"
        },
        unit="cm**2 / volt / second",
    )
    carrier_concentration = Quantity(
        type=np.float64,
        description='FILL',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "1 / cm**3"
        },
        unit="1 / cm**3",
    )


class HallMeasurements(SectionReference):
    '''
    A section used for referencing a HallMeasurement.
    '''
    reference = Quantity(
        type=HallMeasurement,
        description='A reference to a NOMAD `HallMeasurement` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Hall Measurement Reference',
        ),
    )


class SubstrateInventory(TableData, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)
    substrate_data_file = Quantity(
        type=str,
        description='Upload here the spreadsheet file containing the growth data',
        a_tabular_parser={
            "parsing_options": {
                "comment": "#"},
            "mapping_options": [
                {
                    "mapping_mode": "row",
                    "file_mode": "multiple_new_entries",
                    "sections": ["substrates"]}]},
        a_browser={
            "adaptor": "RawFileAdaptor"},
        a_eln={
            "component": "FileEditQuantity"},
    )
    substrates = SubSection(
        section_def=Substrates,
        repeats=True,
    )


class SubstratePreparationSteps(Activity):
    '''
    A section used for referencing Activity.
    '''
    m_def = Section()
    substrates = SubSection(
        section_def=Substrates,
        repeats=True,
    )


class Etching(SubstratePreparationSteps, Process, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)
    method = Quantity(
        type=str,
        default="Etching (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    datetime = Quantity(
        type=Datetime,
        description='FILL',
        a_eln={
            "component": "DateTimeEditQuantity",
            "label": "deposition_date"
        },
    )
    temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    elapsed_time = Quantity(
        type=np.float64,
        description='Past time since process started (minutes)',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"
        },
        unit="minute",
    )
    etching_reagents = SubSection(
        section_def=CompositeSystem,
        repeats=True
    )


class Annealing(SubstratePreparationSteps, Process, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)
    method = Quantity(
        type=str,
        default="Annealing (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    datetime = Quantity(
        type=Datetime,
        description='FILL',
        a_eln={
            "component": "DateTimeEditQuantity",
            "label": "deposition_date"
        },
    )
    temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    elapsed_time = Quantity(
        type=np.float64,
        description='Past time since process started (minutes)',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"
        },
        unit="minute",
    )
    anealing_reagents = SubSection(
        section_def=CompositeSystemReference,
    )


class AFMmeasurement(SubstratePreparationSteps, Measurement, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        more={
            "label_quantity": "sample_id"
        },)
    method = Quantity(
        type=str,
        default="AFM (IKZ MOVPE)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Notes"
        },
    )
    image = Quantity(
        type=str,
        description='image showing the thickness measurement points',
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
    sample_id = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    datetime = Quantity(
        type=Datetime,
        a_eln={
            "component": "DateTimeEditQuantity"
        },
    )
    roughness = Quantity(
        type=np.float64,
        description='RMS roughness value obtained by AFM',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "nanometer"
        },
        unit="nanometer",
    )
    surface_features = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )


class AFMmeasurements(SectionReference):
    '''
    A section used for referencing a AFMmeasurement.
    '''
    reference = Quantity(
        type=AFMmeasurement,
        description='A reference to a NOMAD `AFMmeasurement` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='AFM Measurement Reference',
        ),
    )


class LightMicroscope(SubstratePreparationSteps, Measurement, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        more={
            "label_quantity": "sample_id"
        },)
    method = Quantity(
        type=str,
        default="Light Microscope (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity",
            "label": "Notes"
        },
    )
    image = Quantity(
        type=str,
        description='image',
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
    sample_id = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    datetime = Quantity(
        type=Datetime,
        a_eln={
            "component": "DateTimeEditQuantity"
        },
    )


class LiMimeasurements(SectionReference):
    '''
    A section used for referencing a LightMicroscope.
    '''
    reference = Quantity(
        type=LightMicroscope,
        description='A reference to a NOMAD `LightMicroscope` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Light Microscope Measurement Reference',
        ),
    )


class Steps(SectionReference):
    '''
    A section used for referencing SubstratePreparationSteps.
    '''
    reference = Quantity(
        type=SubstratePreparationSteps,
        description='A reference to a NOMAD `SubstratePreparationSteps` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='SubstratePreparationSteps Reference',
        ),
    )


class SubstratePreparation(Process, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)
    method = Quantity(
        type=str,
        default="Substrate Process (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    substrates = SubSection(
        section_def=Substrates,
        repeats=True,
    )
    steps = SubSection(
        section_def=Steps,
        repeats=True,
    )


class MovpeExperimentIMEM(TableData, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)

    growth_data_file = Quantity(
        type=str,
        description='Upload here the spreadsheet file containing the growth data',
        a_tabular_parser={
            "parsing_options": {
                "comment": "#"},
            "mapping_options": [
                {
                    "mapping_mode": "row",
                    "file_mode": "current_entry",
                    "sections": [
                        "#root"
                    ]
                },
                {
                    "mapping_mode": "row",
                    "file_mode": "multiple_new_entries",
                    "sections": [
                        "growth_run/substrate",
                        "substrate",
                        "precursors",

                    ]
                },
                {
                    "mapping_mode": "row",
                    "file_mode": "single_new_entry",
                    "sections": [
                        "pregrowth/pregrowth_steps",
                        "growth_run/growth_run_steps"
                    ]
                },
            ]
        },
        a_browser={
            "adaptor": "RawFileAdaptor"},
        a_eln={
            "component": "FileEditQuantity"},
    )

    method = Quantity(
        type=str,
        default="Experiment (MOVPE IMEM)",
    )
    date = Quantity(
        type=Datetime,
        description='FILL',
        a_tabular={
            "name": "Overview/Date"},
        a_eln={
            "component": "DateTimeEditQuantity"})
    location = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    notes = SubSection(
        section_def=Notes,
    )
    users = SubSection(
        section_def=Users,
    )
    sample = Quantity(
        type=str,
        description='FILL',
        a_tabular={
            "name": "Overview/Sample"},
        a_eln={
            "component": "StringEditQuantity"})
    film = Quantity(
        type=str,
        description='Film material (Material:Dopant species)',
        a_tabular={
            "name": "Overview/Film"},
        a_eln={
            "component": "StringEditQuantity"}
    )
    carrier_gas = Quantity(
        type=str,
        a_tabular={
            "name": "Overview/Carrier Gas"},
        a_eln={
            "component": "StringEditQuantity"}
    )
    VI_III_ratio = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Overview/VI III Ratio"},
        a_eln={
            "component": "StringEditQuantity"}
    )
    growth_time = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Overview/Growth Time"},
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"},
        unit="minute"
    )
    precursors = SubSection(
        section_def=Precursors,
        repeats=True,
    )
    substrate = SubSection(
        section_def=Substrates,
        repeats=True
    )
    pregrowth = SubSection(section_def=Pregrowths)
    growth_run = SubSection(
        section_def=GrowthRuns,
        #repeats=True,
    )
    in_situ_monitoring = SubSection(
        section_def=InSituMonitorings,
    )
    hall_measurement = SubSection(
        section_def=HallMeasurements,
    )
    afm_measurement = SubSection(
        section_def=AFMmeasurements,
    )
    limi_measurement = SubSection(
        section_def=LiMimeasurements,
    )


class HRXRDmeasurement(Measurement, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        more={
            "label_quantity": "sample_id"
        },)
    method = Quantity(
        type=str,
        default="HRXRD (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    sample_id = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    datetime = Quantity(
        type=Datetime,
        a_eln={
            "component": "DateTimeEditQuantity"
        },
    )
    phase = Quantity(
        type=str,
        description='Phase type obtained from HRXRD',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    peak_position_2theta = Quantity(
        type=np.float64,
        description='Peak Position - 2theta',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "degree"
        },
        unit="degree",
    )
    peak_fwhm_2theta = Quantity(
        type=np.float64,
        description='Peak Position - 2theta',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "degree"
        },
        unit="degree",
    )
    peak_position_omega = Quantity(
        type=np.float64,
        description='Peak Position - Omega',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "degree"
        },
        unit="degree",
    )
    peak_fwhm_rocking_curve = Quantity(
        type=str,
        description='Peak FWHM Rocking Curve',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    reflection = Quantity(
        type=str,
        description='Peak FWHM Rocking Curve',
        a_eln={
            "component": "StringEditQuantity"
        },
    )


m_package.__init_metainfo__()
