import numpy as np
import re
from datetime import datetime as dt
import pandas as pd
import json

from nomad.datamodel.metainfo.basesections import (
    ElementalComposition,
    Activity,
    PureSubstance,
    ProcessStep,
    CompositeSystem,
    Measurement,
    MeasurementResult,
    Process,
    Collection,
    EntityReference,
    CompositeSystemReference,
    SectionReference,
    Experiment
)
from nomad.datamodel.metainfo.annotations import (
    ELNAnnotation,
)
from nomad.files import StagingUploadFiles
from nomad.metainfo.metainfo import (
    MProxy,
    QuantityReference
)
from nomad.parsing.tabular import (
    TableData,
    create_archive
)
from structlog.stdlib import (
    BoundLogger,
)
from nomad.metainfo import (
    MSection,
    Package,
    Quantity,
    SubSection,
    MEnum,
    Reference,
    Datetime,
    Section,
    QuantityReference
)
from nomad.datamodel.data import (
    EntryData,
    ArchiveSection,
    Author
)

from nomad.datamodel.datamodel import (
    EntryArchive,
    EntryMetadata
)

from nomad.utils import hash

from laytec_epitt import LayTec_EpiTT_Measurement
from lakeshore import HallMeasurement
from basesections_IKZ import (
    IKZMOVPECategory,
    IKZMOVPE1Category,
    IKZMOVPE2Category
)

m_package = Package(name='movpe_IKZ')


class Notes(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    notes = Quantity(
        type=str,
        a_eln={
            "component": "RichTextEditQuantity"
        },
    )


class Users(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    user = Quantity(
        type=Author,
        a_eln={
            "component": "AuthorEditQuantity"
        },
        shape=["*"],
    )


class ElementalComposition(ElementalComposition):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    element = Quantity(
        type=str,
        a_tabular={
            "name": "Substrate/Elements"
        },
        a_eln={
            "component": "StringEditQuantity"
        },
    )


class Parallelepiped(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    height = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "nanometer"
        },
        unit="nanometer",
    )
    width = Quantity(
        type=np.float64,
        description='substrate dimension X',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        a_tabular={
            "name": "Substrate/Size X"
        },
        unit="millimeter",
    )
    length = Quantity(
        type=np.float64,
        description='substrate dimension Y',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        a_tabular={
            "name": "Substrate/Size Y"
        },
        unit="millimeter",
    )
    surface_area = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 2"
        },
        unit="millimeter ** 2",
    )
    volume = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 3"
        },
        unit="millimeter ** 3",
    )


class Cylinder(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    height = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "nanometer"
        },
        unit="nanometer",
    )
    radius = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        unit="millimeter",
    )
    lower_cap_radius = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        unit="millimeter",
    )
    upper_cap_radius = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        unit="millimeter",
    )
    cap_surface_area = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 2"
        },
        unit="millimeter ** 2",
    )
    lateral_surface_area = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 2"
        },
        unit="millimeter ** 2",
    )
    volume = Quantity(
        type=np.float64,
        description='docs',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter ** 3"
        },
        unit="millimeter ** 3",
    )


class Geometry(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)
    parallelepiped = SubSection(
        section_def=Parallelepiped,
    )
    cylinder = SubSection(
        section_def=Cylinder,
    )


class Precursor(PureSubstance, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        categories=[IKZMOVPECategory]
        )
    name = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Substance Name"
        },
    )
    cas_number = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
            "label": "CAS number"
        },
    )


class Precursors(EntityReference):
    '''
    A section used for referencing a Precursor.
    '''
    reference = Quantity(
        type=Precursor,
        description='A reference to a NOMAD `Precursor` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Precursor Reference',
        ),
    )


class Substrate(CompositeSystem, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''

    m_def = Section(
        label_quantity='lab_id',
        categories=[IKZMOVPECategory],
    )

    # name = Quantity(
    #     type=str,
    #     description='FILL',
    #     a_eln={
    #         "component": "StringEditQuantity"
    #     },
    #     a_tabular={
    #         "name": "Substrate/Substrates"
    #     },
    # )

    delivery_date = Quantity(
        type=Datetime,
        description='Date of the delivery',
        a_eln={
            "component": "DateTimeEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Delivery Date"
        },
    )
    lab_id = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Substrates"
        },
    )
    supplier = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Supplier"
        },
    )
    orientation = Quantity(
        type=str,
        description='crystallographic orientation of the substrate in [hkl]',
        a_eln={
            "component": "StringEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Orientation"
        },
    )
    miscut_b_angle = Quantity(
        type=str,
        description='crystallographic orientation of the substrate in [hkl]',
        a_eln={
            "component": "StringEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Miscut b angle"
        },
    )
    miscut_c_angle = Quantity(
        type=str,
        description='crystallographic orientation of the substrate in [hkl]',
        a_eln={
            "component": "StringEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Miscut c angle"
        },
    )
    miscut_c_orientation = Quantity(
        type=str,
        description='crystallographic orientation of the substrate in [hkl]',
        a_eln={
            "component": "StringEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Miscut c Orientation"
        },
    )
    doping_level = Quantity(
        type=np.float64,
        description='Chemical doping level of electrically conductive substrates',
        a_eln={
            "component": "NumberEditQuantity"},
        a_tabular={
            "name": "Substrate/Doping Level"},
    )
    doping_species = Quantity(
        type=str,
        description='Doping species to obtain electrical conductivity in the substrates',
        a_eln={
            "component": "StringEditQuantity"},
        a_tabular={
            "name": "Substrate/Doping species"},
    )
    as_received = Quantity(
        type=bool,
        description='Is the sample annealed?',
        a_eln={
            "component": "BoolEditQuantity"
        },
        a_tabular={
            "name": "Substrate/As Received"
        },
    )
    etching = Quantity(
        type=bool,
        description='Usable Sample',
        a_eln={
            "component": "BoolEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Etching"
        },
    )
    annealing = Quantity(
        type=bool,
        description='Usable Sample',
        a_eln={
            "component": "BoolEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Annealing"
        },
    )
    annealing_temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Substrate/Annealing Temperature"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    re_etching = Quantity(
        type=bool,
        description='Usable Sample',
        a_eln={
            "component": "BoolEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Re-Etching"
        },
    )
    re_annealing = Quantity(
        type=bool,
        description='Usable Sample',
        a_eln={
            "component": "BoolEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Re-Annealing"
        },
    )
    epi_ready = Quantity(
        type=bool,
        description='Sample ready for epitaxy',
        a_eln={
            "component": "BoolEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Epi Ready"
        },
    )
    box = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Box"
        },
    )
    quality = Quantity(
        type=str,
        description='Defective Sample',
        a_eln={
            "component": "StringEditQuantity"
        },
        a_tabular={
            "name": "Substrate/Quality"
        },
    )
    documentation = Quantity(
        type=str,
        description='pdf files containing certificate and other documentation',
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
    notes = Quantity(
        type=str,
        description='Notes and comments.',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Notes"
        },
    )
    geometry = SubSection(
        section_def=Geometry,
    )
    elemental_composition = SubSection(
        section_def=ElementalComposition,
        repeats=True,
    )


class Substrates(CompositeSystemReference):
    '''
    A section used for referencing a Substrate.
    '''

    lab_id = Quantity(
        type=str,
        description='the Substrate used for the growth',
        a_tabular={
            "name": "GrowthRun/Substrate Name"
        },
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Substrate ID',
        ),
    )

    reference = Quantity(
        type=Substrate,
        description='A reference to a NOMAD `Substrate` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Substrate Reference',
        ),
    )

    # def normalize(self, archive, logger: BoundLogger) -> None:
    #     '''
    #     The normalizer for the `Substrates` class.
    #     '''
    #     super(Substrates, self).normalize(archive, logger)

        # if self.reference:
        #     setattr(self,'name', self.reference.lab_id)


class ParentSamples(CompositeSystemReference):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    lab_id = Quantity(
        type=str,
        description='the sample used for this step of growth',
        a_tabular={
            "name": "GrowthRun/Previous Layer Name"
        },
        a_eln=ELNAnnotation(
             component='StringEditQuantity',
             label= "Previous Layer ID"
        ),
    )
    reference = Quantity(
        type=CompositeSystem,
        description='A reference to a NOMAD `ParentSample` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Parent Sample Reference',
        ),
    )


class GrownSample(CompositeSystem, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        more={
            "label_quantity": "lab_id"
        },
        categories=[IKZMOVPECategory],
        label='Grown Sample',
        )
    lab_id = Quantity(
        type=str,
        description='the Sample created in the current growth',
        a_tabular={
            "name": "GrowthRun/Sample Name"
        },
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Grown Sample ID',
        ),
    )
    test_quantities = Quantity(
        type=str,
        description='Test quantity',
        a_eln={
            "component": "StringEditQuantity"
        },
    )


class GrownSamples(CompositeSystemReference):
    '''
    A section used for referencing a Grown Sample.
    '''
    lab_id = Quantity(
        type=str,
        description='the Sample created in the current growth',
        a_tabular={
            "name": "GrowthRun/Sample Name"
        },
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Grown Sample ID',
        ),
    )
    reference = Quantity(
        type=GrownSample,
        description='A reference to a NOMAD `GrownSample` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='GrownSample Reference',
        ),
    )
    def normalize(self, archive, logger: BoundLogger) -> None:
        '''
        The normalizer for the `GrownSamples` class.
        '''
        super(GrownSamples, self).normalize(archive, logger)

class Bubbler(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        # more={
        #     "label_quantity": "material"
        # },
        )
    name = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Material"
        },
        a_eln={
            "component": "StringEditQuantity",
            "label": "Material"
        },
    )
    mass_flow_controller = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler MFC"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    pressure = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Pressure"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )
    dilution = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Dilution"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    source = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Source"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    inject = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Inject"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Temp"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )
    partial_pressure = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Partial Pressure"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )
    molar_flux = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Bubbler Molar Flux"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mol / minute"
        },
        unit="mol / minute",
    )


class GasSource(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        more={
            "label_quantity": "material"
        },)
    material = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Gas Material"
        },
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    mass_flow_controller = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Gas MFC"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    molar_flux = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Gas Molar Flux"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )


class GrowthStepMovpe2IKZ(ProcessStep):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,)
    name = Quantity(
        type=str,
        description='''
        A short and descriptive name for this step.
        ''',
        a_tabular={
            "name": "GrowthRun/Step name"
        },
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Step name',
        ),
    )
    step_index = Quantity(
        type=str,
        description='the ID from RTG',
        a_tabular={
            "name": "GrowthRun/Step Index"
        },
        a_eln={
            "component": "StringEditQuantity",
        },
    )
    elapsed_time = Quantity(
        type=np.float64,
        description='Past time since process start',
        a_tabular={
            "name": "GrowthRun/Duration"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"
        },
        unit="minute",
    )
    temperature_shaft = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/T Shaft"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    temperature_filament = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/T Filament"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    temperature_laytec = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/T LayTec"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    pressure = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Pressure"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )
    rotation = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Rotation"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "rpm"
        },
        unit="rpm",
    )
    carrier_gas = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Carrier Gas"
        },
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    push_gas_valve = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Pushgas Valve"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    uniform_valve = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Uniform Valve"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    showerhead_distance = Quantity(
        type=np.float64,
        description='inner valve (0-200)',
        a_tabular={
            "name": "GrowthRun/Distance of Showerhead"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "millimeter"
        },
        unit="millimeter",
    )
    comments = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "GrowthRun/Comments"
        },
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    bubblers = SubSection(
        section_def=Bubbler,
        repeats=True,
    )
    gas_source = SubSection(
        section_def=GasSource,
        repeats=True,
    )


class GrowthMovpe2IKZ(Process, EntryData, TableData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "hide": [
                "samples"
            ]
        },
        more={
            "label_quantity": "growth_id"
        },
        categories=[IKZMOVPE2Category],
        label='Growth',
    )
    data_file = Quantity(
        type=str,
        description='Upload here the spreadsheet file containing the growth data',
        a_tabular_parser={
            "parsing_options": {
                "comment": "#"},
            "mapping_options": [
                {
                    "mapping_mode": "row",
                    "file_mode": "multiple_new_entries",
                    "sections": [
                        "#root"
                    ]
                }
            ]
        },
        a_browser={
            "adaptor": "RawFileAdaptor"},
        a_eln={
            "component": "FileEditQuantity"},
    )
    method = Quantity(
        type=str,
        default="Growth (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    lab_id = Quantity(
        type=str,
        description='the ID from RTG',
        a_tabular={
            "name": "GrowthRun/Recipe Name"
        },
        a_eln={
            "component": "StringEditQuantity",
            "label": "Recipe ID"
        },
    )
    recipe_id = Quantity(
        type=GrownSample.lab_id,
        # a_eln={
        #     #"component": "StringEditQuantity",
        #     "label": "Growth ID"
        # },
        default="#/data/grown_sample/lab_id"
    )
    grown_sample = SubSection(
        section_def=GrownSamples,
        # repeats=True
    )
    parent_sample = SubSection(
        section_def=ParentSamples,
        repeats=True
    )
    substrate = SubSection(
        section_def=Substrates,
        repeats=True
    )
    steps = SubSection(
        section_def=GrowthStepMovpe2IKZ,
        repeats=True,
    )


class GrowthsMovpe2IKZ(SectionReference):
    '''
    A section used for referencing a GrowthMovpe2.
    '''
    reference = Quantity(
        type=GrowthMovpe2IKZ,
        description='A reference to a NOMAD `GrowthMovpe2` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='GrowthMovpe2 Reference',
        ),
    )


class GrowthStepMovpe1IKZ(ProcessStep):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        categories=[IKZMOVPE1Category],
    )
    name = Quantity(
        type=str,
        description='''
        A short and descriptive name for this step.
        ''',
        a_tabular={
            "name": "Constant Parameters/Reason"
        },
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Step name',
        ),
    )
    step_index = Quantity(
        type=str,
        description='the step index',
        a_tabular={
            "name": "Constant Parameters/Step Index"
        },
        a_eln={
            "component": "StringEditQuantity",
        },
    )
    duration = Quantity(
        type=np.float64,
        description='step duration',
        a_tabular={
            "name": "Constant Parameters/Duration"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"
        },
        unit="minute",
    )
    temperature_shaft = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Shaft temperature"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    temperature_substrate = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Substrate temperature"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    pressure = Quantity(
        type=np.float64,
        description='chamber pressure',
        a_tabular={
            "name": "Constant Parameters/Chamber pressure"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "mbar"
        },
        unit="mbar",
    )
    rotation = Quantity(
        type=np.float64,
        description='carrier rotation',
        a_tabular={
            "name": "Constant Parameters/Carrier rotation"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "rpm"
        },
        unit="rpm",
    )
    argon_flow = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Argon flow"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    oxygen_flow = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Oxygen flow"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    argon_push_titan = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Argon push Titan"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    argon_purge_titan = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Argon purge Titan"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    vaporization_T_titan = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Vaporization temperature Titan"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    peristaltic_pump_rotation_titan = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Peristaltic pump rotation Titan"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    argon_push_Sr_La = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Argon push Sr La"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    argon_purge_Sr_La = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Argon purge Sr La"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "cm ** 3 / minute"
        },
        unit="cm ** 3 / minute",
    )
    vaporization_T_Sr_La = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Vaporization temperature Sr La"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    peristaltic_pump_rotation_Sr_La = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Peristaltic pump rotation Sr La"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )

    comments = Quantity(
        type=str,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Constant Parameters/Comment"
        },
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    # bubblers = SubSection(
    #     section_def=Bubbler,
    #     repeats=True,
    # )
    # gas_source = SubSection(
    #     section_def=GasSource,
    #     repeats=True,
    # )


class GrowthMovpe1IKZ(Process, EntryData, TableData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "hide": [
                "samples"
            ]
        },
        more={
            "label_quantity": "growth_id"
        },
        categories=[IKZMOVPE1Category],
        label='Growth',
    )
    data_file = Quantity(
        type=str,
        description='Upload here the spreadsheet file containing the growth data',
        a_tabular_parser={
            "parsing_options": {
                "comment": "#"},
            "mapping_options": [
                {
                    "mapping_mode": "row",
                    "file_mode": "current_entry",
                    "sections": [
                        "steps"
                    ]
                }
            ]
        },
        a_browser={
            "adaptor": "RawFileAdaptor"},
        a_eln={
            "component": "FileEditQuantity"},
    )
    method = Quantity(
        type=str,
        default="Growth (MOVPE 1 IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    lab_id = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Constant Parameters ID"
        },
    )
    # precursors = SubSection(
    #     section_def=Precursors,
    #     repeats=True,
    # )
    # grown_sample = SubSection(
    #     section_def=GrownSamples,
    #     # repeats=True
    # )
    # parent_sample = SubSection(
    #     section_def=ParentSamples,
    #     repeats=True
    # )
    # substrate = SubSection(
    #     section_def=Substrates,
    #     repeats=True
    # )
    steps = SubSection(
        section_def=GrowthStepMovpe1IKZ,
        repeats=True,
    )


class FilamentTemperature(ArchiveSection):
    '''
    Filament Tempearture vs. Time
    '''
    m_def = Section(
        more={
            "label_quantity": "time"
        },
    )
    time = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Deposition Control/Fil time"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"
        },
        unit="minute",
    )
    filament_temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_tabular={
            "name": "Deposition Control/Fil T"
        },
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )


class DepositionControlMovpe1IKZ(Process, EntryData, TableData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        more={
            "label_quantity": "lab_id"
        },
        categories=[IKZMOVPE1Category],
    )
    data_file = Quantity(
        type=str,
        description='Upload here the spreadsheet file containing the deposition control data',
        a_tabular_parser={
            "parsing_options": {
                "comment": "#"},
            "mapping_options": [
                {
                    "mapping_mode": "row",
                    "file_mode": "multiple_new_entries",
                    "sections": [
                        "#root"
                    ]
                }
            ]
        },
        a_browser={
            "adaptor": "RawFileAdaptor"},
        a_eln={
            "component": "FileEditQuantity"},
    )
    method = Quantity(
        type=str,
        default="Deposition Control (MOVPE 1 IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    # datetime = Quantity(
    #     type=Datetime,
    #     a_tabular={
    #         "name": "Deposition Control/Datum"
    #     },
    #     a_eln={
    #         "component": "DateTimeEditQuantity"
    #     },
    # )
    lab_id = Quantity(
        type=str,
        description='FILL',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Grown Sample ID"
        },
    )
    filament_temperature = SubSection(
        section_def=FilamentTemperature,
        repeats=True,
    )
    # grown_sample = SubSection(
    #     section_def=GrownSamples,
    #     # repeats=True
    # )


class GrowthsMovpe1IKZ(SectionReference):
    '''
    A section used for referencing a GrowthMovpe1IKZ.
    '''
    reference = Quantity(
        type=GrowthMovpe1IKZ,
        description='A reference to a NOMAD `GrowthMovpe1IKZ` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='GrowthMovpe1IKZ Reference',
        ),
    )


class InSituMonitorings(SectionReference):
    '''
    A section used for referencing a InSituMonitoring.
    '''
    reference = Quantity(
        type=LayTec_EpiTT_Measurement,
        description='A reference to a NOMAD `InSituMonitoring` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='In situ Monitoring Reference',
        ),
    )


class HallMeasurements(SectionReference):
    '''
    A section used for referencing a HallMeasurement.
    The class is taken from the dedicated Lakeshore plugin
    '''
    reference = Quantity(
        type=HallMeasurement,
        description='A reference to a NOMAD `HallMeasurement` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Hall Measurement Reference',
        ),
    )


class SubstrateInventory(EntryData, TableData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        categories=[IKZMOVPECategory],
        label='Substrate Inventory',
    )
    substrate_data_file = Quantity(
        type=str,
        description='Upload here the spreadsheet file containing the substrates data',
        a_tabular_parser={
            "parsing_options": {
                "comment": "#"},
            "mapping_options": [
                {
                    "mapping_mode": "row",
                    "file_mode": "multiple_new_entries",
                    "sections": ["substrates"]}]},
        a_browser={
            "adaptor": "RawFileAdaptor"},
        a_eln={
            "component": "FileEditQuantity"},
    )
    substrates = SubSection(
        section_def=Substrates,
        repeats=True,
    )


class SubstratePreparationSteps(Activity):
    '''
    A section used for referencing Activity.
    '''
    m_def = Section()
    # substrates = SubSection(
    #     section_def=Substrates,
    #     repeats=True,
    # )


class Etching(SubstratePreparationSteps, Process, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        categories=[IKZMOVPE2Category],
    )
    method = Quantity(
        type=str,
        default="Etching (MOVPE IKZ)",
    )
    datetime = Quantity(
        type=Datetime,
        description='FILL',
        a_eln={
            "component": "DateTimeEditQuantity",
            "label": "deposition_date"
        },
    )
    temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    elapsed_time = Quantity(
        type=np.float64,
        description='Past time since process started (minutes)',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"
        },
        unit="minute",
    )
    etching_reagents = SubSection(
        section_def=CompositeSystem,
        repeats=True
    )


class Annealing(SubstratePreparationSteps, Process, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        categories=[IKZMOVPE2Category],
    )
    method = Quantity(
        type=str,
        default="Annealing (MOVPE IKZ)",
    )
    datetime = Quantity(
        type=Datetime,
        description='FILL',
        a_eln={
            "component": "DateTimeEditQuantity",
            "label": "deposition_date"
        },
    )
    temperature = Quantity(
        type=np.float64,
        description='FILL THE DESCRIPTION',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "celsius"
        },
        unit="celsius",
    )
    elapsed_time = Quantity(
        type=np.float64,
        description='Past time since process started (minutes)',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "minute"
        },
        unit="minute",
    )
    anealing_reagents = SubSection(
        section_def=CompositeSystemReference,
    )


class AFMresults(MeasurementResult):
    '''
    The results of an AFM measurement
    '''
    roughness = Quantity(
        type=np.float64,
        description='RMS roughness value obtained by AFM',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "picometer"
        },
        unit="picometer",
    )
    surface_features = Quantity(
        type=MEnum(['Step Flow',
                    'Step Bunching',
                    '2D Island'
                    ]),
        a_eln={
            "component": "EnumEditQuantity"
        },
    )
    scale = Quantity(
        type=np.float64,
        description='scale of the image, to be multiplied by 5 to know the image size',
        a_eln={
            "component": "NumberEditQuantity",
            "defaultDisplayUnit": "nanometer"
        },
        unit="nanometer",
    )
    image = Quantity(
        type=str,
        description='image showing the thickness measurement points',
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
    crop_image = Quantity(
        type=str,
        description='crop image ready to be used for AI-based analysis',
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )


class AFMmeasurement(SubstratePreparationSteps, Measurement, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "hide": [
                "steps"
            ]
        },
        categories=[IKZMOVPE2Category],
        label='AFM',
    )
    method = Quantity(
        type=str,
        default="AFM (IKZ MOVPE)",
    )
    description = Quantity(
        type=str,
        a_eln={
            "component": "RichTextEditQuantity"
        },
    )
    datetime = Quantity(
        type=Datetime,
        a_eln={
            "component": "DateTimeEditQuantity"
        },
    )
    results = SubSection(
        section_def=AFMresults,
        repeats=True,
    )


class AFMmeasurements(SectionReference):
    '''
    A section used for referencing a AFMmeasurement.
    '''
    reference = Quantity(
        type=AFMmeasurement,
        description='A reference to a NOMAD `AFMmeasurement` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='AFM Measurement Reference',
        ),
    )


class LiMiresults(MeasurementResult):
    '''
    The results of a Light Microscope measurement
    '''
    image = Quantity(
        type=str,
        description='image showing the thickness measurement points',
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
    crop_image = Quantity(
        type=str,
        description='crop image ready to be used for AI-based analysis',
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )


class LightMicroscope(SubstratePreparationSteps, Measurement, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        more={
            "label_quantity": "sample_id"
        },
        categories=[IKZMOVPE2Category],
        label='Light Microscope',
    )
    method = Quantity(
        type=str,
        default="Light Microscope (MOVPE IKZ)",
    )
    sample_id = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    datetime = Quantity(
        type=Datetime,
        a_eln={
            "component": "DateTimeEditQuantity"
        },
    )
    results = SubSection(
        section_def=LiMiresults,
        repeats=True,
    )


class LiMimeasurements(SectionReference):
    '''
    A section used for referencing a LightMicroscope.
    '''
    reference = Quantity(
        type=LightMicroscope,
        description='A reference to a NOMAD `LightMicroscope` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='Light Microscope Measurement Reference',
        ),
    )


class Steps(SectionReference):
    '''
    A section used for referencing SubstratePreparationSteps.
    '''
    reference = Quantity(
        type=SubstratePreparationSteps,
        description='A reference to a NOMAD `SubstratePreparationSteps` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='SubstratePreparationSteps Reference',
        ),
    )


class SubstratePreparation(Process, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        categories=[IKZMOVPECategory],
    )
    method = Quantity(
        type=str,
        default="Substrate Process (MOVPE IKZ)",
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    substrates = SubSection(
        section_def=Substrates,
        repeats=True,
    )
    steps = SubSection(
        section_def=Steps,
        repeats=True,
    )


class ExperimentMovpe2IKZ(Experiment, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        categories=[IKZMOVPE2Category],
        label='Experiment',
    )
    method = Quantity(
        type=str,
        default="Experiment (MOVPE 2 IKZ)",
    )
    location = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    lab_id = Quantity(
        type=str,
        description='the ID from RTG',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Recipe ID"
        },
    )
    date = Quantity(
        type=Datetime,
        description='FILL',
        a_eln={
            "component": "DateTimeEditQuantity"
        },
    )
    notes = SubSection(
        section_def=Notes,
    )
    users = SubSection(
        section_def=Users,
    )
    precursors = SubSection(
        section_def=Precursors,
        repeats=True,
    )
    growth_run = SubSection(
        section_def=GrowthsMovpe2IKZ,
        repeats=True,
    )
    in_situ_monitoring = SubSection(
        section_def=InSituMonitorings,
        repeats=True,
    )
    hall_measurement = SubSection(
        section_def=HallMeasurements,
        repeats=True,
    )
    afm_measurement = SubSection(
        section_def=AFMmeasurements,
        repeats=True,
    )
    limi_measurement = SubSection(
        section_def=LiMimeasurements,
        repeats=True,
    )


class ExperimentMovpe1IKZ(Experiment, EntryData):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln=None,
        categories=[IKZMOVPE1Category],
        label='Experiment',
    )
    method = Quantity(
        type=str,
        default="Experiment (MOVPE 1 IKZ)",
    )
    location = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    lab_id = Quantity(
        type=str,
        description='the ID from RTG',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Recipe ID"
        },
    )
    date = Quantity(
        type=Datetime,
        description='FILL',
        a_eln={
            "component": "DateTimeEditQuantity"
        },
    )
    notes = SubSection(
        section_def=Notes,
    )
    users = SubSection(
        section_def=Users,
    )
    growth_run = SubSection(
        section_def=GrowthsMovpe1IKZ,
        repeats=True,
    )
    in_situ_monitoring = SubSection(
        section_def=InSituMonitorings,
        repeats=True,
    )
    hall_measurement = SubSection(
        section_def=HallMeasurements,
        repeats=True,
    )
    afm_measurement = SubSection(
        section_def=AFMmeasurements,
        repeats=True,
    )
    limi_measurement = SubSection(
        section_def=LiMimeasurements,
        repeats=True,
    )
    # def normalize(self, archive, logger: BoundLogger) -> None:
    #     '''
    #     The normalizer for the `MovpeBinaryOxidesIKZExperiment` class.
    #     '''
    #     super(MovpeBinaryOxidesIKZExperiment, self).normalize(archive, logger)
    ## Potential weak code in next lines:
    ## I want to get back to GrowthRun entry (already created by tabular parser)
    ## and set the "reference" quantity in grwon_samples.
    ## Here two example codes by Theodore Chang, first touches the raw file, second touches the processed file.
    #### ONE
    ## 1. get the file name of archive/entry containing grown_sample_ref
    ## 2. overwrite yaml for this entry
    ## 3. reprocess
    # grown_sample_ref.reference = f'../uploads/{archive.m_context.upload_id}/archive/{hash(archive.m_context.upload_id, filename)}#data'
    # grown_sample_archive = grown_sample_ref
    # while not isinstance(grown_sample_archive, EntryArchive):
    #     grown_sample_archive=grown_sample_archive.m_parent
    # grown_sample_file_name:str = grown_sample_archive.metadata.mainfile
    # create_archive(
    #     grown_sample_archive.m_to_dict(), archive.m_context, grown_sample_file_name, filetype, logger,bypass_check=True)
    #### TWO
    ## alternatively directly overwite the processed msg file
    # grown_sample_upload_id:str = grown_sample_archive.metadata.upload_id
    # grown_sample_entry_id:str = grown_sample_archive.metadata.entry_id
    # StagingUploadFiles(grown_sample_upload_id).write_archive(grown_sample_entry_id, grown_sample_archive.m_to_dict())


# class HRXRDmeasurement(Measurement, EntryData):
#     '''
#     Class autogenerated from yaml schema.
#     '''
#     m_def = Section(
#         a_eln=None,
#         more={
#             "label_quantity": "sample_id"
#         },
#         categories=[IKZMOVPE2Category],
#     )
#     method = Quantity(
#         type=str,
#         default="HRXRD (MOVPE IKZ)",
#     )
#     description = Quantity(
#         type=str,
#         description='description',
#         a_eln={
#             "component": "StringEditQuantity"
#         },
#     )
#     sample_id = Quantity(
#         type=str,
#         a_eln={
#             "component": "StringEditQuantity"
#         },
#     )
#     datetime = Quantity(
#         type=Datetime,
#         a_eln={
#             "component": "DateTimeEditQuantity"
#         },
#     )
#     phase = Quantity(
#         type=str,
#         description='Phase type obtained from HRXRD',
#         a_eln={
#             "component": "StringEditQuantity"
#         },
#     )
#     peak_position_2theta = Quantity(
#         type=np.float64,
#         description='Peak Position - 2theta',
#         a_eln={
#             "component": "NumberEditQuantity",
#             "defaultDisplayUnit": "degree"
#         },
#         unit="degree",
#     )
#     peak_fwhm_2theta = Quantity(
#         type=np.float64,
#         description='Peak Position - 2theta',
#         a_eln={
#             "component": "NumberEditQuantity",
#             "defaultDisplayUnit": "degree"
#         },
#         unit="degree",
#     )
#     peak_position_omega = Quantity(
#         type=np.float64,
#         description='Peak Position - Omega',
#         a_eln={
#             "component": "NumberEditQuantity",
#             "defaultDisplayUnit": "degree"
#         },
#         unit="degree",
#     )
#     peak_fwhm_rocking_curve = Quantity(
#         type=str,
#         description='Peak FWHM Rocking Curve',
#         a_eln={
#             "component": "StringEditQuantity"
#         },
#     )
#     reflection = Quantity(
#         type=str,
#         description='Peak FWHM Rocking Curve',
#         a_eln={
#             "component": "StringEditQuantity"
#         },
#     )


m_package.__init_metainfo__()
