import numpy as np
import yaml
import json
import math

from nomad.datamodel.data import EntryData, EntryDataCategory

from nomad.metainfo import Package, Quantity, SubSection, Datetime, Section, Category

from nomad.datamodel.metainfo.basesections import (
    CompositeSystem,
    System,
    Activity,
    ActivityStep,
    Process,
    CompositeSystemReference,
    PureSubstanceSection,
)

from nomad.datamodel.metainfo.annotations import (
    ELNAnnotation,
    ELNComponentEnum,
)

from nomad.utils import hash

from ikz_plugin.utils import create_archive

m_package = Package(name="basesections_IKZ")


class IKZCategory(EntryDataCategory):
    m_def = Category(label="IKZ", categories=[EntryDataCategory])


class IKZMOVPECategory(EntryDataCategory):
    m_def = Category(label="MOVPE", categories=[EntryDataCategory, IKZCategory])


class IKZMOVPE1Category(EntryDataCategory):
    m_def = Category(label="MOVPE 1", categories=[EntryDataCategory, IKZCategory])


class IKZMOVPE2Category(EntryDataCategory):
    m_def = Category(label="MOVPE 2", categories=[EntryDataCategory, IKZCategory])


class IKZDSCategory(EntryDataCategory):
    m_def = Category(
        label="Directional Solidification", categories=[EntryDataCategory, IKZCategory]
    )


class IKZHallCategory(EntryDataCategory):
    m_def = Category(label="Hall", categories=[EntryDataCategory, IKZCategory])


class SubstratePreparationStep(Activity):
    """
    A section used for referencing Activities performed on Substrate.
    """

    m_def = Section()


class SolutionPreparationStep(Activity):
    """
    A section used for referencing Activities performed on Substrate.
    """

    m_def = Section()


class QuantifyMaterial(Process, EntryData):  #### TODO it overlaps with Component class
    """
    Weigh or pipette a material.
    """

    alias = Quantity(
        type=str,
        a_eln={"component": "StringEditQuantity"},
    )
    container_mass = Quantity(
        type=float,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "gram"},
        unit="gram",
    )
    net_mass = Quantity(
        type=float,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "gram"},
        unit="gram",
    )
    brutto_mass = Quantity(
        type=float,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "gram"},
        unit="gram",
    )
    reference = Quantity(
        type=System,
        description="A reference to a NOMAD `CompositeSystem` entry.",
        a_eln=ELNAnnotation(
            component="ReferenceEditQuantity",
            label="Composite System Reference",
        ),
    )


# Weighing
class QuantifySolidMaterial(QuantifyMaterial, SolutionPreparationStep, EntryData):
    """
    Class autogenerated from yaml schema.
    """

    m_def = Section(
        a_eln=None,
        categories=[IKZCategory],
    )
    # molecular_weight


# Pipetting
class QuantifyLiquidMaterial(QuantifyMaterial, SolutionPreparationStep, EntryData):
    """
    Class autogenerated from yaml schema.
    """

    m_def = Section(
        a_eln=None,
        categories=[IKZCategory],
    )
    measured_volume = Quantity(
        type=float,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "liter"},
        unit="liter",
    )
    density = Quantity(
        type=float,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "gram / liter"},
        unit="gram / liter",
    )
    # molecular_weight


class MixMaterial(Process, SolutionPreparationStep, EntryData):
    """
    Mix the quantified materials.
    """

    m_def = Section(
        a_eln=None,
        categories=[IKZCategory],
    )
    alias = Quantity(
        type=str,
        a_eln={"component": "StringEditQuantity"},
    )
    mixed_aliases = Quantity(
        type=str,
        a_eln={"component": "StringEditQuantity"},
    )
    mixing_time = Quantity(
        type=float,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "second"},
        unit="second",
    )
    temperature = Quantity(
        type=np.float64,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "celsius"},
        unit="celsius",
    )
    container_type = Quantity(
        type=str,
        a_eln={"component": "StringEditQuantity"},
    )
    rotation_speed = Quantity(
        type=float,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "rpm"},
        unit="rpm",
    )
    mixed_material = SubSection(
        description="""
        The mixed material.
        """,
        section_def=CompositeSystem,
    )


class SolutionPreparationIKZ(Process, EntryData):
    """
    Solution preparation class
    """

    description = Quantity(
        type=str,
        a_eln={"component": "StringEditQuantity"},
    )
    atmosphere = Quantity(
        type=str,
        a_eln={"component": "StringEditQuantity"},
    )
    intended_sample_conc = Quantity(  # TODO make this a single flow
        type=np.float64,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "mol / liter"},
        unit="mol / liter",
    )
    obtained_conc = Quantity(  # TODO make this a single flow
        type=np.float64,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "mol / liter"},
        unit="mol / liter",
    )
    intended_tot_volume = Quantity(  # TODO make this a single flow
        type=np.float64,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "mol / liter"},
        unit="mol / liter",
    )
    obtained_tot_volume = Quantity(  # TODO make this a single flow
        type=np.float64,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "mol / liter"},
        unit="mol / liter",
    )
    steps = SubSection(
        section_def=SolutionPreparationStep,
        repeats=True,
    )


class EtchingStep(ActivityStep):
    """
    A step of etching process.
    """

    m_def = Section()
    duration = Quantity(
        type=float,
        unit="second",
        description="Past time since process started (minutes)",
    )
    temperature = Quantity(
        type=np.float64,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "celsius"},
        unit="celsius",
    )
    etching_reagents = SubSection(section_def=CompositeSystem, repeats=True)


class Etching(Process, SubstratePreparationStep, EntryData):
    """
    Class autogenerated from yaml schema.
    """

    m_def = Section(
        a_eln=None,
        categories=[IKZCategory],
    )
    method = Quantity(
        type=str,
        default="Etching (MOVPE IKZ)",
    )
    datetime = Quantity(
        type=Datetime,
        description="FILL",
        a_eln={"component": "DateTimeEditQuantity", "label": "deposition_date"},
    )
    steps = SubSection(
        description="""
        The steps of the etching process.
        """,
        section_def=EtchingStep,
        repeats=True,
    )


class Annealing(Process, SubstratePreparationStep, EntryData):
    """
    Class autogenerated from yaml schema.
    """

    m_def = Section(
        a_eln=None,
        categories=[IKZCategory],
    )
    method = Quantity(
        type=str,
        default="Annealing (MOVPE IKZ)",
    )
    datetime = Quantity(
        type=Datetime,
        description="FILL",
        a_eln={"component": "DateTimeEditQuantity", "label": "deposition_date"},
    )
    temperature = Quantity(
        type=np.float64,
        description="FILL THE DESCRIPTION",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "celsius"},
        unit="celsius",
    )
    elapsed_time = Quantity(
        type=np.float64,
        description="Past time since process started (minutes)",
        a_eln={"component": "NumberEditQuantity", "defaultDisplayUnit": "minute"},
        unit="minute",
    )
    anealing_reagents = SubSection(
        section_def=CompositeSystemReference,
    )


class SampleCutIKZ(Process, EntryData):
    """
    An Activity that can be used for cutting a sample in multiple ones.
    """

    m_def = Section(
        a_eln={"hide": ["steps", "samples", "instruments"]},
        label="Sample Cut",
        categories=[IKZCategory],
    )
    number_of_samples = Quantity(
        type=int,
        description='The number of samples generated from this "Sample Cut" Task.',
        a_eln=dict(component="NumberEditQuantity"),
    )
    parent_sample = SubSection(
        description="""
        The parent sample that is going to be cut.
        """,
        section_def=CompositeSystemReference,
    )
    children_samples = SubSection(
        description="""
        The children samples that are going to be created.
        """,
        section_def=CompositeSystemReference,
        repeats=True,
    )

    def normalize(self, archive, logger):
        from nomad.datamodel import EntryArchive, EntryMetadata

        super(SampleCutIKZ, self).normalize(archive, logger)
        filetype = "yaml"
        if not self.number_of_samples:
            logger.error(
                f"Error in SampleCut: 'number_of_samples' expected, but None found."
            )
        if not self.parent_sample:
            logger.error(
                f"Error in SampleCut: 'parent_sample' expected, but None found."
            )
        if self.children_samples:
            logger.error(
                f"Error in SampleCut: No children samples expected,"
                f" but {len(self.children_samples)} children samples given."
                f" Remove the children samples and save again."
            )
        generated_samples = []
        if self.parent_sample and self.number_of_samples:
            for sample_index in range(self.number_of_samples):
                children_filename = f"{self.parent_sample.reference.lab_id}_child{sample_index}.CompositeSystem.archive.{filetype}"
                children_object = self.parent_sample.reference.m_copy(deep=True)
                children_object.name = (
                    f"{self.parent_sample.reference.lab_id}_child{sample_index}"
                )
                children_object.lab_id = (
                    f"{self.parent_sample.reference.lab_id}_child{sample_index}"
                )
                children_archive = EntryArchive(
                    data=children_object,
                    m_context=archive.m_context,
                    metadata=EntryMetadata(upload_id=archive.m_context.upload_id),
                )
                create_archive(
                    children_archive.m_to_dict(),
                    archive.m_context,
                    children_filename,
                    filetype,
                    logger,
                )
                generated_samples.append(
                    CompositeSystemReference(
                        name=children_object.name,
                        reference=f"../uploads/{archive.m_context.upload_id}/archive/{hash(archive.m_context.upload_id, children_filename)}#data",
                    ),
                )
            self.children_samples = generated_samples


m_package.__init_metainfo__()
